name: provider
description: A wrapper around InheritedWidget to make them easier to use and more reusable.
version: 6.0.2
repository: https://github.com/rrousselGit/provider

environment:
  sdk: ">=2.7.2 <3.0.0"
  flutter: ">=1.12.13"

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter
  nested: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  test: ^1.15.5
